### ISSUE TITLE
Group Project: Setup Kanban board

### ISSUE THREAD

**Issue by Bondok6** [algerina/recipe-app#10]
We have created our Kanban board, [Link to project](https://github.com/algerina/recipe-app/projects/1) 

Team member 1: @algerina 
Team member 2: @Bondok6

**Comment by dasileker** [comment]
### **Hi @algerina,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
